spring.application.name=final-project


spring.datasource.url=jdbc:mysql://sh-cdb-oehpnutq.sql.tencentcdb.com:29364/instrument?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=TJSE_instrument
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# pay
payment.url=https://2218466.pay.lanjingzf.com
payment.create-order=https://2218466.pay.lanjingzf.com/createOrder
payment.secret-key=db28171e41c0d68e51e1ce5e26f6962f
payment.notify-url=https://ad1480459efa8b.lhr.life/api/payment/callback
payment.return-url=http://localhost:8081/product/1

demo.enabled=false
